// Code generated by ifacemaker; DO NOT EDIT.

package tallylogic

// BoardController ...
type BoardController interface {
	GetCellAtIndex(n int) *Cell
	FindCell(c Cell) (int, bool)
	String() string
	PrintBoard(highlighter func(c Cell, index int, padded string) string) string
	ValidCellIndex(index int) bool
	CoordToIndex(x, y int) (int, bool)
	ValidatePath(indexes []int) (err error, invalidIndex int)
	EvaluatesTo(indexes []int) (int64, EvalMethod, error)
	SwipeDirection(direction SwipeDirection) bool
	SwipeDirectionPreview(direction SwipeDirection) []Cell
	AreNeighboursByIndex(a, b int) bool
	NeighboursForCellIndex(index int) ([]int, bool)
}
