services:
  db:
    image: mysql:8.0.30-debian
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tallyboard
