# fly.toml file generated for gotally on 2022-08-14T18:42:07+02:00

app = "gotally"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[deploy]
strategy = "rolling"

[env]
OTEL_SERVICE_NAME = "gotally"
OTEL_ENVIRONMENT_NAME = "production"
# HONEYCOMB_API_KEY="set-with-fly-secret"
# DSN="set-with-fly-secret"

[experimental]
allowed_public_ports = []
auto_rollback = true

[metrics]
port = 8080       # default for most prometheus clients
path = "/metrics" # default for most prometheus clients

[[services]]
http_checks = []
internal_port = 8080
processes = ["app"]
protocol = "tcp"
script_checks = []
[services.concurrency]
hard_limit = 999999
soft_limit = 999999
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[mounts]
source = "data"
destination = "/app/data"
