// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package sqlite

import (
	"database/sql"
	"time"
)

type Game struct {
	ID          string
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
	Description sql.NullString
	UserID      string
	RuleID      string
	Score       int64
	Moves       int64
	PlayState   int64
	Data        []byte
}

type GameHistory struct {
	CreatedAt time.Time
	GameID    string
	Move      int64
	Kind      int64
	Points    int64
	Data      []byte
}

type Rule struct {
	ID              string
	Slug            string
	CreatedAt       time.Time
	UpdatedAt       sql.NullTime
	Mode            int64
	Description     sql.NullString
	SizeX           int64
	SizeY           int64
	RecreateOnSwipe bool
	NoReswipe       bool
	NoMultiply      bool
	NoAddition      bool
}

type Session struct {
	ID           string
	CreatedAt    time.Time
	UpdatedAt    sql.NullTime
	InvalidAfter time.Time
	UserID       string
}

type User struct {
	ID           string
	CreatedAt    time.Time
	UpdatedAt    sql.NullTime
	Username     string
	ActiveGameID string
}
