<script lang="ts">
	import { SwipeDirection } from '../../connect-web'

	export let instruction: SwipeDirection | undefined
	export let active: boolean
	const getSwipeText = (d: SwipeDirection | undefined) => {
		console.log('swipeText', d)
		switch (d) {
			case SwipeDirection.UP:
				return 'Up'
			case SwipeDirection.RIGHT:
				return 'Right'
			case SwipeDirection.DOWN:
				return 'Down'
			case SwipeDirection.LEFT:
				return 'Left'
		}
		return ''
	}
	$: swipetext = getSwipeText(instruction)
</script>

<div class="wrapper" class:active>
	<div
		class="shadow"
		class:up={instruction === SwipeDirection.UP}
		class:right={instruction === SwipeDirection.RIGHT}
		class:down={instruction === SwipeDirection.DOWN}
		class:left={instruction === SwipeDirection.LEFT}
	>
		<!-- Generated by IcoMoon.io -->
		<div>
			<svg
				version="1.1"
				xmlns="http://www.w3.org/2000/svg"
				width="24"
				height="24"
				viewBox="0 0 24 24"
			>
				<path
					fill="currentColor"
					d="M12 0.752c-6.213 0-11.25 5.037-11.25 11.25s5.037 11.25 11.25 11.25 11.25-5.037 11.25-11.25-5.037-11.25-11.25-11.25zM18.894 18.896c-1.757 1.752-4.182 2.835-6.859 2.835-5.365 0-9.715-4.349-9.715-9.715s4.349-9.715 9.715-9.715c5.365 0 9.715 4.349 9.715 9.715 0 1.365-0.282 2.664-0.79 3.843l0.024-0.063c-0.517 1.205-1.222 2.234-2.090 3.099l-0 0z"
				/>
				<path
					fill="currentColor"
					d="M12.779 7.734l-1.061-1.061-5.329 5.329 5.329 5.329 1.061-1.061-3.518-3.518h8.786v-1.5h-8.786l3.518-3.518z"
				/>
			</svg>
		</div>
	</div>
</div>

<style>
	/* Glow-effect by Dave Brogan https://codepen.io/davebrogan/pen/OJJKXpy */
	.wrapper {
		pointer-events: none;
		z-index: 1;
		position: absolute;
		font-size: 3rem;
		left: 0;
		right: 0;
		bottom: 0;
		top: 0;
		opacity: 0;
		display: flex;
		justify-content: center;
		align-items: center;
		text-align: center;
		transform: scale(0.4);
		animation-name: pulse;
		animation-duration: 1.3s;
		animation-direction: both;
		animation-iteration-count: infinite;
		margin: auto;
		color: var(--color-blue-300);
		font-size: 3rem;
	}
	svg {
		width: 100px;
		height: 100px;
	}
	.active {
		opacity: 0.9;
	}
	@keyframes bounce {
		0%,
		20%,
		55%,
		75%,
		100% {
			-webkit-transform: translateY(0);
		}
		40% {
			-webkit-transform: translateY(-125px);
		}
		60% {
			-webkit-transform: translateY(-85px);
		}
	}
	@keyframes pulse {
		0% {
			transform: scale(1);
		}
		50% {
			transform: scale(1.1);
		}
		100% {
			transform: scale(1);
		}
	}

	.left svg {
		transform: rotate(0deg);
	}
	.right svg {
		transform: rotate(180deg);
	}
	.down svg {
		transform: rotate(-90deg);
	}
	.up svg {
		transform: rotate(90deg);
	}
</style>
